project_name: sub2clash
builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - windows
          - linux
          - darwin
      goarch:
          - amd64
          - arm64
          - "386"
      ldflags:
          - -s -w -X sub2clash/config.Version={{ .Version }}
      no_unique_dist_dir: true
      binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
archives:
    - format: binary
